#!/usr/bin/env bash
# Generate .github/workflows/harness-ci.yml for this project.
# Run once per project. Re-run to update if harness changes.
#
# Usage: ci-generate.sh <project_root> [--staging-url <url>]
#
# Generated workflow:
#   on PR push:    qa-gate --fast + post results as PR comment
#   on PR open:    auto-deploy staging (via deploy-config.sh)
#   manual:        deploy production (requires GitHub Environment approval)

set -euo pipefail

PROJECT_ROOT="${1:-$(git -C "$(pwd)" rev-parse --show-toplevel 2>/dev/null || pwd)}"
STAGING_URL="${2:-https://staging.example.com}"

WORKFLOW_DIR="$PROJECT_ROOT/.github/workflows"
mkdir -p "$WORKFLOW_DIR"

log() { echo "[ci-generate] $*" >&2; }

cat > "$WORKFLOW_DIR/harness-ci.yml" << WORKFLOW
# Generated by execution-harness scripts/ci-generate.sh
# Regenerate: ~/.claude/skills/execution-harness/scripts/ci-generate.sh <project_root>

name: Harness CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      confirm_production:
        description: 'Type CONFIRM to deploy production'
        required: false

jobs:
  qa-gate:
    name: QA Gate
    runs-on: ubuntu-latest
    outputs:
      verdict: \${{ steps.gate.outputs.verdict }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: npm }
      - run: npm ci
      - run: npx playwright install --with-deps chromium

      - name: Build + start preview
        run: npm run build && npx serve dist -p 4173 &
      - run: npx wait-on http://localhost:4173 --timeout 30000

      - name: ATDD tests
        run: npx playwright test tests/e2e/ux-contracts/ --reporter=junit
        continue-on-error: true
      - name: Behavior tests
        run: npx vitest run tests/unit/ux-contracts/ --reporter=junit
        continue-on-error: true

      - name: Security scan (SAST, zero LLM tokens)
        run: bash ~/.claude/skills/execution-harness/scripts/security-scan.sh \${{ github.workspace }} --changed-only || true

      - name: QA gate
        id: gate
        run: |
          bash ~/.claude/skills/execution-harness/scripts/qa-gate.sh \${{ github.workspace }} http://localhost:4173 --fast
          echo "verdict=\$(python3 -c \"import json; print(json.load(open('.harness/qa-gate.json'))['verdict'])\")" >> \$GITHUB_OUTPUT

      - name: Post gate result as PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const gate = JSON.parse(require('fs').readFileSync('.harness/qa-gate.json'))
            const icon = gate.verdict === 'GO' ? '✅' : '❌'
            const rows = gate.checks.map(c =>
              \`| \${c.status==='PASS'?'✓':c.status==='SKIP'?'~':'✗'} | \${c.check} | \${c.detail} |\`
            ).join('\\n')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner, repo: context.repo.repo,
              body: \`## \${icon} QA Gate: \${gate.verdict}\\n\\n| | Check | Detail |\\n|---|---|---|\\n\${rows}\`
            })

      - uses: actions/upload-artifact@v4
        if: always()
        with: { name: harness-artifacts, path: .harness/ }

  deploy-staging:
    name: Deploy Staging
    needs: qa-gate
    if: needs.qa-gate.outputs.verdict == 'GO' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          DEPLOY_KEY: \${{ secrets.STAGING_DEPLOY_KEY }}
        run: source deploy-config.sh && eval "\$DEPLOY_STAGING_CMD"
      - name: Health check
        run: |
          for i in 1 2 3; do
            HTTP=\$(curl -s -o /dev/null -w "%{http_code}" ${STAGING_URL}/api/health || echo 000)
            [ "\$HTTP" = "200" ] && break || sleep 5
          done; [ "\$HTTP" = "200" ]
      - name: Post staging URL
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner, repo: context.repo.repo,
              body: '🚀 Staging: ${STAGING_URL}'
            })

  deploy-production:
    name: Deploy Production
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm_production == 'CONFIRM'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          DEPLOY_KEY: \${{ secrets.PROD_DEPLOY_KEY }}
        run: source deploy-config.sh && eval "\$DEPLOY_PROD_CMD"
WORKFLOW

log "Generated: $WORKFLOW_DIR/harness-ci.yml"
log ""
log "Setup checklist:"
log "  1. GitHub → Settings → Environments → create 'staging' + 'production'"
log "  2. Add secrets: STAGING_DEPLOY_KEY, PROD_DEPLOY_KEY"
log "  3. Replace 'npm run build && npx serve dist' with your build command"
log "  4. Replace staging URL: ${STAGING_URL}"
log "  5. git add .github/ && git commit -m 'ci: add harness CI workflow'"
