#!/usr/bin/env python3
"""
fe-behavior-test-generate.py — Testing Trophy Gap 3: generate Vue Test Utils behavior tests.

Testing Trophy principle: find elements by ROLE/LABEL (what user sees), not by CSS class
or component internals. Tests describe behavior, not implementation.

These are INTEGRATION tests in the Testing Trophy — more than unit tests, fewer than E2E.
They run in Vitest + @vue/test-utils without a browser.

Usage:
  python3 fe-behavior-test-generate.py ux-contracts/invoice-list.yaml --output tests/unit/ux-contracts/
  python3 fe-behavior-test-generate.py ux-contracts/ --output tests/unit/ux-contracts/  (batch)

Output: TypeScript test file per screen using @vue/test-utils + Testing Library queries
"""

import sys
import re
import argparse
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Error: pyyaml not installed. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def component_name_from_screen(screen: str) -> str:
    return ''.join(w.capitalize() for w in re.split(r'[-_]', screen))


def gen_import_block(screen: str, component_name: str) -> str:
    return f"""// AUTO-GENERATED by fe-behavior-test-generate.py from ux-contracts/{screen}.yaml
// Testing Trophy: INTEGRATION behavior tests (find by role/label, not by CSS class)
// Run with: vitest run tests/unit/ux-contracts/{screen}.test.ts
// All tests FAIL before implementation. Make them green.

import {{ describe, it, expect, vi }} from 'vitest'
import {{ mount, flushPromises }} from '@vue/test-utils'
import {{ createPinia }} from 'pinia'
// TODO: update import path to match your component location
import {component_name} from '@/components/{component_name}.vue'

const pinia = createPinia()
const mountComponent = (props = {{}}, stubs = {{}}) =>
  mount({component_name}, {{
    global: {{ plugins: [pinia], stubs }},
    props,
  }})
"""


def gen_empty_state_tests(screen: str, component_name: str, states: dict) -> str:
    if 'empty' not in states:
        return ''
    items = states['empty'].get('required', [])
    parts = [f"\ndescribe('{component_name} — empty state (Testing Trophy: behavior)', () => {{"]
    parts.append(f"""  it('renders accessible CTA when data is empty', async () => {{
    const wrapper = mountComponent({{ items: [], loading: false, error: null }})
    await flushPromises()
    // Find by role — not by .empty-state class
    const button = wrapper.find('[role="button"]')
    expect(button.exists()).toBe(true)
    expect(button.text()).toMatch(/buat|tambah|add|create/i)
  }})

  it('empty text is descriptive, not just No data', async () => {{
    const wrapper = mountComponent({{ items: [], loading: false, error: null }})
    await flushPromises()
    expect(wrapper.text()).not.toMatch(/^no data$/im)
    expect(wrapper.text()).not.toContain('undefined')
  }})
""")
    parts.append('})')
    return '\n'.join(parts)


def gen_loading_state_tests(screen: str, component_name: str) -> str:
    return f"""
describe('{component_name} — loading state (Testing Trophy: behavior)', () => {{
  it('shows loading indicator accessible by aria-busy', async () => {{
    const wrapper = mountComponent({{ loading: true }})
    const loadingEl = wrapper.find('[aria-busy="true"], [data-testid*="skeleton"], .skeleton')
    expect(loadingEl.exists()).toBe(true)
  }})

  it('disables primary action while loading', async () => {{
    const wrapper = mountComponent({{ loading: true }})
    const buttons = wrapper.findAll('button')
    if (buttons.length > 0) {{
      // Primary action button should be disabled during load
      expect(buttons[0].attributes('disabled')).toBeDefined()
    }}
  }})
}})
"""


def gen_error_state_tests(screen: str, component_name: str) -> str:
    return f"""
describe('{component_name} — error state (Testing Trophy: behavior)', () => {{
  it('renders error with accessible role=alert', async () => {{
    const wrapper = mountComponent({{ error: 'Something went wrong', loading: false }})
    await flushPromises()
    const alert = wrapper.find('[role="alert"]')
    expect(alert.exists()).toBe(true)
    expect(alert.text()).not.toContain('undefined')
    expect(alert.text()).not.toMatch(/\\.js:\\d+/) // no stack trace
  }})

  it('provides retry action accessible by role', async () => {{
    const mockRetry = vi.fn()
    const wrapper = mountComponent({{ error: 'Error', onRetry: mockRetry }})
    await flushPromises()
    const retryBtn = wrapper.find('[role="button"]')
    if (retryBtn.exists()) {{
      await retryBtn.trigger('click')
      // Either emits retry event or calls handler
      expect(
        wrapper.emitted('retry') || mockRetry.mock.calls.length > 0
      ).toBeTruthy()
    }}
  }})
}})
"""


def gen_data_state_tests(screen: str, component_name: str, states: dict) -> str:
    if 'data' not in states:
        return ''
    cols = states['data'].get('columns', [])
    col_list = ', '.join(f'"{c}"' for c in cols[:4]) if cols else '"Col1"'
    return f"""
describe('{component_name} — data state (Testing Trophy: behavior)', () => {{
  const sampleItems = [
    {{ id: 1, status: 'active' }},
    {{ id: 2, status: 'inactive' }},
  ]

  it('renders data rows accessible by role=row', async () => {{
    const wrapper = mountComponent({{ items: sampleItems, loading: false }})
    await flushPromises()
    const rows = wrapper.findAll('[role="row"]')
    // header row + 2 data rows
    expect(rows.length).toBeGreaterThanOrEqual(2)
  }})

  it('table columns match contract: {col_list}', async () => {{
    const wrapper = mountComponent({{ items: sampleItems, loading: false }})
    await flushPromises()
    const headerRow = wrapper.find('[role="row"]:first-child, thead tr')
    if (headerRow.exists()) {{
      const text = headerRow.text()
      // Columns from ux-contract: {col_list}
      // TODO: assert specific column headers from your contract
      expect(text.length).toBeGreaterThan(0)
    }}
  }})
}})
"""


def gen_interaction_tests(screen: str, component_name: str, journeys: list) -> str:
    if not journeys:
        return ''
    parts = [f"\ndescribe('{component_name} — interactions (Testing Trophy: behavior)', () => {{"]
    for journey in journeys[:3]:
        jid = journey.get('id', 'action')
        steps = journey.get('steps', [])
        triggers = [s for s in steps if s.startswith('trigger:')]
        expects = [s for s in steps if s.startswith('expect:')]
        if not triggers:
            continue
        trigger = triggers[0].replace('trigger:', '').strip()
        btn = re.search(r'"([^"]+)"', trigger)
        btn_name = btn.group(1) if btn else 'primary action'

        parts.append(f"""  it('{jid}: user can trigger {btn_name}', async () => {{
    const wrapper = mountComponent({{ items: [], loading: false }})
    await flushPromises()
    // Find by accessible name — not by CSS class
    const btn = wrapper.find(`[aria-label*="{btn_name}"], [role="button"]`)
    if (btn.exists()) {{
      await btn.trigger('click')
      // TODO: assert expected outcome for journey {jid}
      // Expected: {expects[0].replace('expect:', '').strip() if expects else 'modal opens or action triggered'}
      expect(wrapper.emitted()).toBeDefined()
    }}
  }})
""")
    parts.append('})')
    return '\n'.join(parts)


def generate_test_file(contract_path: Path) -> str:
    with open(contract_path) as f:
        contract = yaml.safe_load(f)

    if contract.get('status', 'draft') != 'approved':
        return None

    screen = contract.get('screen', contract_path.stem)
    component = component_name_from_screen(screen)
    states = contract.get('states', {})
    journeys = contract.get('journeys', [])

    return (
        gen_import_block(screen, component)
        + gen_loading_state_tests(screen, component)
        + gen_empty_state_tests(screen, component, states)
        + gen_error_state_tests(screen, component)
        + gen_data_state_tests(screen, component, states)
        + gen_interaction_tests(screen, component, journeys)
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('input', help='YAML contract or directory')
    parser.add_argument('--output', '-o', default='tests/unit/ux-contracts')
    args = parser.parse_args()

    input_path = Path(args.input)
    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)

    paths = list(input_path.glob('*.yaml')) if input_path.is_dir() else [input_path]
    generated = skipped = 0

    for p in sorted(paths):
        try:
            content = generate_test_file(p)
        except Exception as e:
            print(f"  SKIP {p.name}: {e}", file=sys.stderr)
            skipped += 1
            continue

        if content is None:
            print(f"  SKIP {p.name}: status not approved")
            skipped += 1
            continue

        out_path = out_dir / f"{p.stem}.test.ts"
        out_path.write_text(content)
        print(f"  {out_path} — behavior tests (find by role, not class)")
        generated += 1

    print(f"\nGenerated {generated} behavior test files, skipped {skipped}")
    print("Run: vitest run tests/unit/ux-contracts/")


if __name__ == '__main__':
    main()
